platform :ios, "8.0"
use_frameworks!

target 'Eventy' do

pod 'Alamofire', '~> 2.0'
pod 'Locksmith', :git => 'https://github.com/matthewpalmer/Locksmith.git', :branch => '2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'
pod 'AlamofireImage', '~> 1.0'
pod 'HanekeSwift'
pod 'HockeySDK', '~> 3.8.2'

end

